<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class pbbh extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('pbbhs')->insert([
            "umur"=>1,
            "pbbh"=>17,
            "eph"=>121,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>2,
            "pbbh"=>19,
            "eph"=>106,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>3,
            "pbbh"=>21,
            "eph"=>95,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>4,
            "pbbh"=>25,
            "eph"=>93,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>5,
            "pbbh"=>27,
            "eph"=>93,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>6,
            "pbbh"=>28,
            "eph"=>85,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>7,
            "pbbh"=>30,
            "eph"=>81,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>8,
            "pbbh"=>32,
            "eph"=>80,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>9,
            "pbbh"=>35,
            "eph"=>81,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>10,
            "pbbh"=>40,
            "eph"=>80,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>11,
            "pbbh"=>45,
            "eph"=>79,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>12,
            "pbbh"=>51,
            "eph"=>80,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>13,
            "pbbh"=>57,
            "eph"=>79,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>14,
            "pbbh"=>58,
            "eph"=>78,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>15,
            "pbbh"=>61,
            "eph"=>78,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>16,
            "pbbh"=>65,
            "eph"=>76,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>17,
            "pbbh"=>68,
            "eph"=>75,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>18,
            "pbbh"=>70,
            "eph"=>68,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>19,
            "pbbh"=>73,
            "eph"=>66,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>20,
            "pbbh"=>76,
            "eph"=>67,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>21,
            "pbbh"=>77,
            "eph"=>65,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>22,
            "pbbh"=>78,
            "eph"=>63,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>23,
            "pbbh"=>80,
            "eph"=>63,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>24,
            "pbbh"=>82,
            "eph"=>62,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>25,
            "pbbh"=>83,
            "eph"=>61,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>26,
            "pbbh"=>84,
            "eph"=>58,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>27,
            "pbbh"=>85,
            "eph"=>57,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>28,
            "pbbh"=>86,
            "eph"=>55,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>29,
            "pbbh"=>87,
            "eph"=>54,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>30,
            "pbbh"=>88,
            "eph"=>54,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>31,
            "pbbh"=>89,
            "eph"=>53,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>32,
            "pbbh"=>90,
            "eph"=>53,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>33,
            "pbbh"=>92,
            "eph"=>53,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>34,
            "pbbh"=>93,
            "eph"=>53,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>35,
            "pbbh"=>95,
            "eph"=>53,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>36,
            "pbbh"=>96,
            "eph"=>53,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>37,
            "pbbh"=>97,
            "eph"=>52,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>38,
            "pbbh"=>97,
            "eph"=>51,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>39,
            "pbbh"=>98,
            "eph"=>51,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>40,
            "pbbh"=>98,
            "eph"=>50,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>41,
            "pbbh"=>97,
            "eph"=>48,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>42,
            "pbbh"=>97,
            "eph"=>47,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>43,
            "pbbh"=>97,
            "eph"=>46,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>44,
            "pbbh"=>96,
            "eph"=>44,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>45,
            "pbbh"=>96,
            "eph"=>43,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>46,
            "pbbh"=>96,
            "eph"=>42,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>47,
            "pbbh"=>95,
            "eph"=>41,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>48,
            "pbbh"=>94,
            "eph"=>40,
        ]);
        DB::table('pbbhs')->insert([
            "umur"=>49,
            "pbbh"=>93,
            "eph"=>39,
        ]);


    }
}
